export const resumeData = {
  personalInfo: {
    name: "Prashant Kumar",
    title: "Software Engineer at Jai Infoway",
    summary:
      "Skilled MERN Stack Developer with 3 years of experience crafting full-stack web applications. Proficient in PostgreSQL, Express.js, React.js, Next.js, Node.js, and TypeScript, with a strong focus on scalable architecture and high-performance APIs. Dedicated to clean code, continuous improvement, and building responsive, maintainable solutions that solve real-world challenges. Thrives in agile teams, values collaboration, and brings a passion for innovation and problem-solving to every project.",
    email: "niraj2kumar4@gmail.com",
    phone: "9155828823",
    location: "Bengaluru, Karnataka, India",
    linkedin: "https://www.linkedin.com/in/prashant-kumar",
  },
  workExperience: [
    {
      title: "Software Engineer",
      company: "Jai Infoway Pvt Ltd",
      duration: "11/2022 - Present",
      location: "Ranchi",
      responsibilities: [
        "Engineered scalable and high-performance backend services using Node.js, Express, and Sequelize, leading to a 30% improvement in API response times and enabling seamless integration with web and mobile ecosystems.",
        "Architected reusable middleware, helper utilities, and modular service layers to improve code maintainability, reduce technical debt, and accelerate development cycles.",
        "Designed and deployed robust RESTful APIs with complete CRUD operations, and integrated Stripe to handle complex billing workflows, including subscriptions, payments, refunds, and webhook event handling.",
        "Managed transactional integrity across distributed systems by leveraging Sequelize’s transaction features with PostgreSQL, ensuring data accuracy and consistency under high concurrency.",
        "Implemented advanced backend features such as lazy loading, refresh token-based authentication, referral contact management, WebSocket-powered real-time messaging, Redis-based caching, server push notifications, and live GPS tracking integration.",
        "Optimized performance through SQL query optimization, caching layers (Redis/memory), and scalable service-oriented architecture, improving system scalability and reducing load times.",
        "Developed modern, component-driven frontends using React.js, building reusable UI components and maintaining clean, scalable architecture for both web and mobile platforms.",
        "Enhanced frontend performance through memoization (React.memo, useMemo), code splitting, and lazy loading, resulting in faster page loads and improved UX.",
        "Implemented secure and dynamic forms using React Hook Form with custom validations, reducing form-related bugs and improving data integrity.",
        "Integrated REST APIs using Axios/Fetch and React Hooks, delivering real-time data updates and interactive user experiences across multiple modules.",
        "Configured React Router DOM for efficient single-page application (SPA) navigation with protected routes and user role-based access control.",
        "Improved system observability by implementing error tracking, logging, and alerting mechanisms using tools like Winston, Sentry, and Loggly, streamlining bug detection and resolution across environments.",
      ],
    },
  ],
  skills: [
    "PostgreSQL",
    "Express.js",
    "React.js",
    "Next.js",
    "Node.js",
    "TypeScript",
    "RESTful APIs",
    "Sequelize",
    "Redis",
    "WebSocket",
    "Stripe",
    "React Hook Form",
    "Axios",
    "React Router DOM",
    "Winston",
    "Sentry",
    "Loggly",
  ],
  tools: ["GIT", "Visual Studio Code", "Microsoft", "Jira", "Confluence", "ChatGPT"],
  education: {
    degree: "Masters in Computer Application (MCA)",
    institution: "Marwari College",
    location: "Ranchi, Jharkhand",
    duration: "04/2017 - 04/2020",
  },
  languages: [
    { name: "English", proficiency: "Full Professional Proficiency" },
    { name: "Hindi", proficiency: "Full Professional Proficiency" },
  ],
};